version: '3.9'
services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: signage
      MARIADB_USER: signage
      MARIADB_PASSWORD: signage
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ${MEDIA_PATH:-./media}:/var/lib/signage/media
    ports:
      - '3000:3000'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api
    ports:
      - '5173:5173'

volumes:
  db_data:
  media:
